# Generated by Django 5.2.8 on 2025-11-23 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailsendler", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mailgetter",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mailmailing",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mailmessage",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailmailing",
            name="end_time",
            field=models.DateTimeField(verbose_name="Дата/Время окончания"),
        ),
        migrations.AlterField(
            model_name="mailmailing",
            name="start_time",
            field=models.DateTimeField(verbose_name="Дата/Время начала"),
        ),
        migrations.AlterField(
            model_name="mailmailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("running", "Запущена"),
                    ("finished", "Завершена"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
