# Generated by Django 5.2.8 on 2025-11-24 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "mailsendler",
            "0002_mailgetter_owner_mailmailing_owner_mailmessage_owner_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailgetter",
            options={
                "permissions": [
                    ("view_all_clients", "Может просматривать всех клиентов")
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="mailmailing",
            options={
                "permissions": [
                    ("view_all_mailings", "Может просматривать все рассылки"),
                    ("dasable_mailings", "Может отключать все рассылки"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="mailmessage",
            options={
                "permissions": [
                    ("view_all_messages", "Может просматривать все сообщения")
                ]
            },
        ),
    ]
