# Generated by Django 5.2.8 on 2025-11-24 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "mailsendler",
            "0003_alter_mailgetter_options_alter_mailmailing_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailmailing",
            options={
                "permissions": [
                    ("view_all_mailings", "Может просматривать все рассылки"),
                    ("dasable_mailings", "Может отключать чужие рассылки"),
                ]
            },
        ),
    ]
